#!/bin/bash
#  Copyright 2014 Michael Caisse : ciere.com
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
#  Run Boost.Test executables and create JUnit flavored output
#
$1 --report_format=xml --report_level=detailed --log_level=test_suite --log_format=xml 2> $1.test.out
xsltproc boost_test_to_junit.xls $1.test.out > $1.test.xml

